# GridCare Project
## Member 1 – Data Engineering

**Student Name:** Dapaah Desmond

**Student ID:** 09902029

### Objective
This notebook focuses on:

- Loading the electricity grid datasets.
- Inspecting and understanding the datasets.
- Cleaning and validating the data.
- Integrating the datasets.
- Preparing the data for graph analysis.

### Datasets

- utilities.csv
- substations.csv
- lines.csv

## 1. Configure Project Paths

Before loading the datasets, I defined the project directories using
`pathlib`. This makes the notebook portable and easier to maintain across
different operating systems. To get future Error raises.

## 2. Loading the datasets

The three datasets are loaded into a Pandas DataFrame
Each DataFrame represents one part of the electricity grid system

In [105]:
from pathlib import Path
import pandas as pd
import numpy as np

NOTEBOOK_DIR = Path.cwd()
PROJECT_ROOT = NOTEBOOK_DIR.parents[1]

# #getting project or folder directory 
# PROJECT_ROOT = Path.cwd().parent
# get the path directory for the folder containing the files
RAW_DATA_DIR = PROJECT_ROOT / "data"/ "raw"
PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"

#loading the files
utilities = pd.read_csv(RAW_DATA_DIR / "utilities.csv")

substations = pd.read_csv(RAW_DATA_DIR / "substations.csv")

lines = pd.read_csv(RAW_DATA_DIR / "lines.csv")

# checking if files have been loaded successfully
print((RAW_DATA_DIR/"utilities.csv").exists())
print((RAW_DATA_DIR / "substations.csv").exists())
print((RAW_DATA_DIR/"lines.csv").exists())

True
True
True

## Inspecting the utilities DataFrames

I inspected the utilities DataFrames to understand its structure, quality and limitations
whether there are missing values or any.

In [106]:
utilities.head()

,Utility ID,Name,Alias,Code,Type,Country,Active
0,1,Electricity Company of Ghana,ECG,ECG,Distribution,Ghana,Y
1,2,Northern Electricity Distribution Company,NEDCo,NED,Distribution,Ghana,Y
2,3,Ghana Grid Company,GRIDCo,GRD,Transmission,Ghana,Y
3,4,Volta River Authority,VRA,VRA,Generation,Ghana,Y
4,5,Compagnie Ivoirienne d'Electricite,CIE,CIE,Distribution,Cote d'Ivoire,Y

In [107]:
utilities.tail()

,Utility ID,Name,Alias,Code,Type,Country,Active
5,6,Communaute Electrique du Benin,CEB,CEB,Transmission,Togo/Benin,Y
6,7,Societe Beninoise d'Energie Electrique,SBEE,SBE,Distribution,Benin,Y
7,8,Electricite de Guinee,EDG,EDG,Distribution,Guinea,N
8,9,Sonabel,SONABEL,SNB,Distribution,Burkina Faso,Y
9,10,Enclave Power Company,EPC,EPC,Generation,Ghana,N

In [108]:
utilities.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Utility ID  10 non-null     int64
 1   Name        10 non-null     str
 2   Alias       10 non-null     str
 3   Code        10 non-null     str
 4   Type        10 non-null     str
 5   Country     10 non-null     str
 6   Active      10 non-null     str
dtypes: int64(1), str(6)
memory usage: 1.2 KB

In [109]:
utilities.describe()

       Utility ID
count    10.00000
mean      5.50000
std       3.02765
min       1.00000
25%       3.25000
50%       5.50000
75%       7.75000
max      10.00000

In [110]:
utilities.isnull().sum()

Utility ID    0
Name          0
Alias         0
Code          0
Type          0
Country       0
Active        0
dtype: int64

In [111]:
utilities.shape

(10, 7)

## Inspecting the substations DataFrames

I inspected the substations DataFrames to understand its structure, quality and limitations
whether there are missing values or any.

In [112]:
substations.head()

,Substation ID,Name,Short Name,Region,Country,Latitude,Longitude,Voltage (kV),Capacity (MVA),Commissioning Year,Type,Status
0,1,Achimota Substation,Achimota,Greater Accra,Ghana,5.6085,-0.2193,11,6.4,2008,Distribution,Active
1,2,Tema Substation,Tema,Greater Accra,Ghana,5.6596,-0.0226,330,48.5,1997,Transmission,Active
2,3,Mallam Substation,Mallam,Greater Accra,Ghana,5.5630,-0.2971,330,25.2,1979,Transmission,Active
3,4,Legon Substation,Legon,Greater Accra,Ghana,5.6401,-0.1799,161,241.9,2009,Transmission,Active
4,5,Kaneshie Substation,Kaneshie,Greater Accra,Ghana,5.5691,-0.2413,161,146.0,1970,Transmission,Active

In [113]:
substations.info()

<class 'pandas.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Substation ID       44 non-null     int64
 1   Name                44 non-null     str
 2   Short Name          44 non-null     str
 3   Region              44 non-null     str
 4   Country             44 non-null     str
 5   Latitude            44 non-null     float64
 6   Longitude           44 non-null     float64
 7   Voltage (kV)        44 non-null     int64
 8   Capacity (MVA)      44 non-null     float64
 9   Commissioning Year  44 non-null     int64
 10  Type                44 non-null     str
 11  Status              44 non-null     str
dtypes: float64(3), int64(3), str(6)
memory usage: 6.9 KB

In [114]:
substations.describe()

,Substation ID,Latitude,Longitude,Voltage (kV),Capacity (MVA),Commissioning Year
count,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000
mean,22.500000,6.898402,-1.194868,134.545455,157.865909,1996.295455
std,12.845233,1.879404,2.314917,120.399810,139.923148,16.112366
min,1.000000,4.874700,-13.580000,11.000000,6.400000,1967.000000
25%,11.750000,5.586350,-1.760000,33.000000,43.825000,1982.250000
50%,22.500000,6.184400,-0.800700,69.000000,108.550000,1999.500000
75%,33.250000,7.364200,-0.170900,161.000000,254.350000,2009.250000
max,44.000000,11.200000,2.430000,330.000000,487.600000,2022.000000

In [115]:
substations.isnull().sum()

Substation ID         0
Name                  0
Short Name            0
Region                0
Country               0
Latitude              0
Longitude             0
Voltage (kV)          0
Capacity (MVA)        0
Commissioning Year    0
Type                  0
Status                0
dtype: int64

In [116]:
substations.shape

(44, 12)

## Inspecting the lines DataFrames

I inspected the substations DataFrames to understand its structure, quality and limitations
whether there are missing values or any.

In [117]:
lines.head()

,Line ID,Utility ID,Source Substation ID,Source Substation,Destination Substation ID,Destination Substation,Voltage (kV),Length (km),Capacity (MVA),Status,Line Type
0,1,2,1,Achimota Substation,2,Tema Substation,11,25.2,215.0,Active,Underground
1,2,2,1,Achimota Substation,3,Mallam Substation,11,11.0,36.4,Active,Overhead
2,3,3,1,Achimota Substation,5,Kaneshie Substation,11,5.9,277.4,Active,Overhead
3,4,1,2,Tema Substation,3,Mallam Substation,330,34.4,39.0,Active,Underground
4,5,3,2,Tema Substation,4,Legon Substation,161,19.5,186.5,Active,Underground

In [118]:
lines.info()

<class 'pandas.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Line ID                    55 non-null     int64
 1   Utility ID                 55 non-null     int64
 2   Source Substation ID       55 non-null     int64
 3   Source Substation          55 non-null     str
 4   Destination Substation ID  55 non-null     int64
 5   Destination Substation     55 non-null     str
 6   Voltage (kV)               55 non-null     int64
 7   Length (km)                55 non-null     float64
 8   Capacity (MVA)             55 non-null     float64
 9   Status                     55 non-null     str
 10  Line Type                  55 non-null     str
dtypes: float64(2), int64(5), str(4)
memory usage: 7.7 KB

In [119]:
lines.describe()

,Line ID,Utility ID,Source Substation ID,Destination Substation ID,Voltage (kV),Length (km),Capacity (MVA)
count,55.00000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000
mean,28.00000,2.836364,17.872727,18.745455,141.381818,99.312727,222.400000
std,16.02082,1.718781,12.060119,11.719275,135.169097,90.275104,109.181765
min,1.00000,1.000000,1.000000,2.000000,11.000000,3.800000,32.900000
25%,14.50000,2.000000,7.500000,9.500000,22.000000,42.900000,134.550000
50%,28.00000,3.000000,16.000000,18.000000,69.000000,75.900000,229.900000
75%,41.50000,3.000000,27.000000,27.000000,330.000000,129.600000,292.100000
max,55.00000,9.000000,40.000000,43.000000,330.000000,426.000000,506.300000

In [120]:
lines.isnull().sum()

Line ID                      0
Utility ID                   0
Source Substation ID         0
Source Substation            0
Destination Substation ID    0
Destination Substation       0
Voltage (kV)                 0
Length (km)                  0
Capacity (MVA)               0
Status                       0
Line Type                    0
dtype: int64

In [121]:
lines.shape

(55, 11)

## Data Validation

I am checking whether the data can be trusted enough before merging it to build a network and then analyse.
I will be checking primary key uniqueness, validity of reference key

In [122]:
# utilities,substations, lines  DataFrame primary key uniqueness

print(f"utilities duplicate Utility ID: {utilities['Utility ID'].duplicated().sum()}")

print(f"substations duplicate Substation ID: {substations['Substation ID'].duplicated().sum()}")

print(f"lines duplicate Line ID: {lines['Line ID'].duplicated().sum()}")
# outputing zero means the primary key is unique

utilities duplicate Utility ID: 0
substations duplicate Substation ID: 0
lines duplicate Line ID: 0

In [123]:
# Validating foriegn keys, especially from the lines DataFrame since it shows relationship

utility_check = lines['Utility ID'].isin(utilities["Utility ID"])
print(f"{utility_check.value_counts()}")

source_check = lines["Source Substation ID"].isin(substations["Substation ID"])
print(f"{source_check.value_counts()}")

destination_check = lines["Destination Substation ID"].isin(substations["Substation ID"])
print(f"{destination_check.value_counts()}")

Utility ID
True    55
Name: count, dtype: int64
Source Substation ID
True    55
Name: count, dtype: int64
Destination Substation ID
True    55
Name: count, dtype: int64

## Data Integration
To effectively analyse the network, i need to merge the separate datasets together to form a relationship.
From the three datasets, they are three different relationships.

 - utilities - lines , connected by the Utility ID
 - substations - lines, connected by Source Substation ID
 - substations - lines, connected by Destination Substation ID

To merge these datasets, there are four ways inner, left, right or outer join.
But since I validated that the datasets are cleaned and has no missing values, I can use any.
In this situation I am using the Left join, where every row in the left table is maintained.

To create my relationships, i asked myself " What is the central object we want to analyse", and that electricity grid networks
### Option A: Utilities

 - each row = one utility
 - Too high level

### Option B: Substations

 - ecah row = one substation
 - good for assets analysis

### Option C: Lines

 - one row = one conncetion
 - Excellent for network analysis, since connections build the network

### For this project
I will build two master tables for future scability and to reduce large tables;
1. Lines Utility Table
 - each row is a transmission or distribution line
 - enriched with utility information 
 
2. Lines Master Table
 - First merge Source Substation ID with Substation ID
 - Then merge Destination Substation ID with Substation ID
 - each row is a transmission line from source to destination 
 - enriched with each substation's information and that of utilities information

In [124]:
print(utilities.columns)
print(substations.columns)
print(lines.columns)
lines_with_utilities = pd.merge(lines, utilities , how = "left", on = "Utility ID")
lines_with_utilities.head()

Index(['Utility ID', 'Name', 'Alias', 'Code', 'Type', 'Country', 'Active'], dtype='str')
Index(['Substation ID', 'Name', 'Short Name', 'Region', 'Country', 'Latitude',
       'Longitude', 'Voltage (kV)', 'Capacity (MVA)', 'Commissioning Year',
       'Type', 'Status'],
      dtype='str')
Index(['Line ID', 'Utility ID', 'Source Substation ID', 'Source Substation',
       'Destination Substation ID', 'Destination Substation', 'Voltage (kV)',
       'Length (km)', 'Capacity (MVA)', 'Status', 'Line Type'],
      dtype='str')

,Line ID,Utility ID,Source Substation ID,Source Substation,Destination Substation ID,Destination Substation,Voltage (kV),Length (km),Capacity (MVA),Status,Line Type,Name,Alias,Code,Type,Country,Active
0,1,2,1,Achimota Substation,2,Tema Substation,11,25.2,215.0,Active,Underground,Northern Electricity Distribution Company,NEDCo,NED,Distribution,Ghana,Y
1,2,2,1,Achimota Substation,3,Mallam Substation,11,11.0,36.4,Active,Overhead,Northern Electricity Distribution Company,NEDCo,NED,Distribution,Ghana,Y
2,3,3,1,Achimota Substation,5,Kaneshie Substation,11,5.9,277.4,Active,Overhead,Ghana Grid Company,GRIDCo,GRD,Transmission,Ghana,Y
3,4,1,2,Tema Substation,3,Mallam Substation,330,34.4,39.0,Active,Underground,Electricity Company of Ghana,ECG,ECG,Distribution,Ghana,Y
4,5,3,2,Tema Substation,4,Legon Substation,161,19.5,186.5,Active,Underground,Ghana Grid Company,GRIDCo,GRD,Transmission,Ghana,Y

In [125]:
# Changing the names of the source and destination substations.
#Since they are all substations hence have similar names, so we have to differentiate them

source_substations = substations.rename(
    columns = {
        'Substation ID': 'Source Substation ID',
        'Name' : 'Substation Name',
        'Short Name':'Source Short Name',
        'Region': 'Source Region',
        'Country': ' Source Country',
        'Latitude' : 'Source Latitude',
        'Longitude': 'Source Longitude',
        'Voltage (kV)':'Source Voltage (kV)',
        'Capacity (MVA)': 'Source Capacity (MVA)',
        'Commissioning Year': 'Source Commissioning Year',
        'Type': 'Source Type',
        'Status': 'Source Status'
        }
)

destination_substations = substations.rename(
    columns = {
        'Substation ID': 'Destination Substation ID',
        'Name': 'Substation Name',
        'Short Name':'Destination Short Name',
        'Region': 'Destination Region',
        'Country': ' Destination Country',
        'Latitude' : 'Destination Latitude',
        'Longitude': 'Destination Longitude',
        'Voltage (kV)':'Destination Voltage (kV)',
        'Capacity (MVA)': 'Destination Capacity (MVA)',
        'Commissioning Year': 'Destination Commissioning Year',
        'Type': 'Destination Type',
        'Status': 'Destination Status'
        })

print(source_substations.columns)
print(destination_substations.columns)

Index(['Source Substation ID', 'Substation Name', 'Source Short Name',
       'Source Region', ' Source Country', 'Source Latitude',
       'Source Longitude', 'Source Voltage (kV)', 'Source Capacity (MVA)',
       'Source Commissioning Year', 'Source Type', 'Source Status'],
      dtype='str')
Index(['Destination Substation ID', 'Substation Name',
       'Destination Short Name', 'Destination Region', ' Destination Country',
       'Destination Latitude', 'Destination Longitude',
       'Destination Voltage (kV)', 'Destination Capacity (MVA)',
       'Destination Commissioning Year', 'Destination Type',
       'Destination Status'],
      dtype='str')

In [126]:
# merging lines_with_utilities and source subastations
lines_with_source = pd.merge(lines_with_utilities, source_substations, how= "left", on="Source Substation ID")
lines_with_source.head()
print(lines_with_source.columns)

Index(['Line ID', 'Utility ID', 'Source Substation ID', 'Source Substation',
       'Destination Substation ID', 'Destination Substation', 'Voltage (kV)',
       'Length (km)', 'Capacity (MVA)', 'Status', 'Line Type', 'Name', 'Alias',
       'Code', 'Type', 'Country', 'Active', 'Substation Name',
       'Source Short Name', 'Source Region', ' Source Country',
       'Source Latitude', 'Source Longitude', 'Source Voltage (kV)',
       'Source Capacity (MVA)', 'Source Commissioning Year', 'Source Type',
       'Source Status'],
      dtype='str')

In [127]:
# merging the results from the above  with destination substations to get the whole network table.
lines_with_source_destination = pd.merge(lines_with_source, destination_substations, how= "left", on="Destination Substation ID")
print(lines_with_source_destination.columns)

lines_with_source_destination.head()

Index(['Line ID', 'Utility ID', 'Source Substation ID', 'Source Substation',
       'Destination Substation ID', 'Destination Substation', 'Voltage (kV)',
       'Length (km)', 'Capacity (MVA)', 'Status', 'Line Type', 'Name', 'Alias',
       'Code', 'Type', 'Country', 'Active', 'Substation Name_x',
       'Source Short Name', 'Source Region', ' Source Country',
       'Source Latitude', 'Source Longitude', 'Source Voltage (kV)',
       'Source Capacity (MVA)', 'Source Commissioning Year', 'Source Type',
       'Source Status', 'Substation Name_y', 'Destination Short Name',
       'Destination Region', ' Destination Country', 'Destination Latitude',
       'Destination Longitude', 'Destination Voltage (kV)',
       'Destination Capacity (MVA)', 'Destination Commissioning Year',
       'Destination Type', 'Destination Status'],
      dtype='str')

,Line ID,Utility ID,Source Substation ID,Source Substation,Destination Substation ID,Destination Substation,Voltage (kV),Length (km),Capacity (MVA),Status,...,Destination Short Name,Destination Region,Destination Country,Destination Latitude,Destination Longitude,Destination Voltage (kV),Destination Capacity (MVA),Destination Commissioning Year,Destination Type,Destination Status
0,1,2,1,Achimota Substation,2,Tema Substation,11,25.2,215.0,Active,...,Tema,Greater Accra,Ghana,5.6596,-0.0226,330,48.5,1997,Transmission,Active
1,2,2,1,Achimota Substation,3,Mallam Substation,11,11.0,36.4,Active,...,Mallam,Greater Accra,Ghana,5.5630,-0.2971,330,25.2,1979,Transmission,Active
2,3,3,1,Achimota Substation,5,Kaneshie Substation,11,5.9,277.4,Active,...,Kaneshie,Greater Accra,Ghana,5.5691,-0.2413,161,146.0,1970,Transmission,Active
3,4,1,2,Tema Substation,3,Mallam Substation,330,34.4,39.0,Active,...,Mallam,Greater Accra,Ghana,5.5630,-0.2971,330,25.2,1979,Transmission,Active
4,5,3,2,Tema Substation,4,Legon Substation,161,19.5,186.5,Active,...,Legon,Greater Accra,Ghana,5.6401,-0.1799,161,241.9,2009,Transmission,Active

In [128]:
lines_with_source_destination.isnull().sum()

Line ID                           0
Utility ID                        0
Source Substation ID              0
Source Substation                 0
Destination Substation ID         0
Destination Substation            0
Voltage (kV)                      0
Length (km)                       0
Capacity (MVA)                    0
Status                            0
Line Type                         0
Name                              0
Alias                             0
Code                              0
Type                              0
Country                           0
Active                            0
Substation Name_x                 0
Source Short Name                 0
Source Region                     0
 Source Country                   0
Source Latitude                   0
Source Longitude                  0
Source Voltage (kV)               0
Source Capacity (MVA)             0
Source Commissioning Year         0
Source Type                       0
Source Status                     0
Substation Name_y                 0
Destination Short Name            0
Destination Region                0
 Destination Country              0
Destination Latitude              0
Destination Longitude             0
Destination Voltage (kV)          0
Destination Capacity (MVA)        0
Destination Commissioning Year    0
Destination Type                  0
Destination Status                0
dtype: int64

In [129]:
# renmaning some colums to prevent confusion

lines_with_source_destination = lines_with_source_destination.rename(
    columns = {
        'Name':'Utility Name',
        'Alias' :"Utility Alias",
        'Code':'Utility Code',
        'Type': 'Utility Type',
        'Country': 'Utility Country',
        'Substation Name_x': 'Source Name',
        'Substation Name_y': 'Destination Name',
        'Length (km)': 'Line Length (km)',
        'Voltage (kV)': 'Line Voltage (kV)',
        'Capacity (MVA)': 'Line Capacity (MVA)',
        'Status': 'Line Status'

    }
)

lines_with_source_destination.columns

Index(['Line ID', 'Utility ID', 'Source Substation ID', 'Source Substation',
       'Destination Substation ID', 'Destination Substation',
       'Line Voltage (kV)', 'Line Length (km)', 'Line Capacity (MVA)',
       'Line Status', 'Line Type', 'Utility Name', 'Utility Alias',
       'Utility Code', 'Utility Type', 'Utility Country', 'Active',
       'Source Name', 'Source Short Name', 'Source Region', ' Source Country',
       'Source Latitude', 'Source Longitude', 'Source Voltage (kV)',
       'Source Capacity (MVA)', 'Source Commissioning Year', 'Source Type',
       'Source Status', 'Destination Name', 'Destination Short Name',
       'Destination Region', ' Destination Country', 'Destination Latitude',
       'Destination Longitude', 'Destination Voltage (kV)',
       'Destination Capacity (MVA)', 'Destination Commissioning Year',
       'Destination Type', 'Destination Status'],
      dtype='str')

## Saving Processed Dataset
Saving the ready processed Pandas DataFrame as a csv file.

In [104]:
# conversion from Pandas DataFrame to csv file
lines_with_source_destination.to_csv("processed_data.csv", index= False)

# checking it was succesful or it exist
Path("processed_data.csv").exists()

True